/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TetrisRouteImport } from './routes/tetris'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTrpcTodoRouteImport } from './routes/demo/trpc-todo'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoPacerRouteImport } from './routes/demo/pacer'
import { Route as DemoAiVoiceRouteImport } from './routes/demo/ai-voice'
import { Route as DemoAiTtsRouteImport } from './routes/demo/ai-tts'
import { Route as DemoAiStructuredRouteImport } from './routes/demo/ai-structured'
import { Route as DemoAiPortfolioRouteImport } from './routes/demo/ai-portfolio'
import { Route as DemoAiImageRouteImport } from './routes/demo/ai-image'
import { Route as ApiResumeChatStreamRouteImport } from './routes/api.resume-chat-stream'
import { Route as ApiResumeChatRouteImport } from './routes/api.resume-chat'
import { Route as ApiLeaderboardRouteImport } from './routes/api/leaderboard'
import { Route as ApiGenerateThreeRouteImport } from './routes/api/generate-three'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DemoGuitarsIndexRouteImport } from './routes/demo/guitars/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoGuitarsCompareRouteImport } from './routes/demo/guitars/compare'
import { Route as DemoGuitarsGuitarIdRouteImport } from './routes/demo/guitars/$guitarId'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form/simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form/address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiWorkersTagsRouteImport } from './routes/api/workers/tags'
import { Route as ApiWorkersSummaryRouteImport } from './routes/api/workers/summary'
import { Route as ApiWorkersSearchRouteImport } from './routes/api/workers/search'
import { Route as ApiWorkersRecommendationsRouteImport } from './routes/api/workers/recommendations'
import { Route as ApiWorkersParseQueryRouteImport } from './routes/api/workers/parse-query'
import { Route as ApiWorkersEmbeddingsRouteImport } from './routes/api/workers/embeddings'
import { Route as ApiWorkersChatRouteImport } from './routes/api/workers/chat'
import { Route as ApiWorkersCategorizeRouteImport } from './routes/api/workers/categorize'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiTetrisLeaderboardRouteImport } from './routes/api/tetris/leaderboard'
import { Route as ApiLeaderboardHistoryRouteImport } from './routes/api/leaderboard/history'
import { Route as ApiGithubStatsRouteImport } from './routes/api/github/stats'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as DemoApiAiTtsStreamRouteImport } from './routes/demo/api.ai.tts-stream'
import { Route as DemoApiAiTtsRouteImport } from './routes/demo/api.ai.tts'
import { Route as DemoApiAiTranscriptionRouteImport } from './routes/demo/api.ai.transcription'
import { Route as DemoApiAiStructuredRouteImport } from './routes/demo/api.ai.structured'
import { Route as DemoApiAiSpeechRouteImport } from './routes/demo/api.ai.speech'
import { Route as DemoApiAiPortfolioRouteImport } from './routes/demo/api.ai.portfolio'
import { Route as DemoApiAiImageRouteImport } from './routes/demo/api/ai/image'
import { Route as ApiWorkersEmbeddingsProtectedExampleRouteImport } from './routes/api/workers/embeddings-protected.example'
import { Route as ApiTetrisLeaderboardHistoryRouteImport } from './routes/api/tetris/leaderboard/history'
import { Route as DemoApiAiGuitarsSearchRouteImport } from './routes/demo/api.ai.guitars.search'
import { Route as DemoApiAiGuitarsCompareRouteImport } from './routes/demo/api.ai.guitars.compare'
import { Route as DemoApiAiGuitarsChatRouteImport } from './routes/demo/api.ai.guitars.chat'

const TetrisRoute = TetrisRouteImport.update({
  id: '/tetris',
  path: '/tetris',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTrpcTodoRoute = DemoTrpcTodoRouteImport.update({
  id: '/demo/trpc-todo',
  path: '/demo/trpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPacerRoute = DemoPacerRouteImport.update({
  id: '/demo/pacer',
  path: '/demo/pacer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiVoiceRoute = DemoAiVoiceRouteImport.update({
  id: '/demo/ai-voice',
  path: '/demo/ai-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiTtsRoute = DemoAiTtsRouteImport.update({
  id: '/demo/ai-tts',
  path: '/demo/ai-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiStructuredRoute = DemoAiStructuredRouteImport.update({
  id: '/demo/ai-structured',
  path: '/demo/ai-structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiPortfolioRoute = DemoAiPortfolioRouteImport.update({
  id: '/demo/ai-portfolio',
  path: '/demo/ai-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiImageRoute = DemoAiImageRouteImport.update({
  id: '/demo/ai-image',
  path: '/demo/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeChatStreamRoute = ApiResumeChatStreamRouteImport.update({
  id: '/api/resume-chat-stream',
  path: '/api/resume-chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeChatRoute = ApiResumeChatRouteImport.update({
  id: '/api/resume-chat',
  path: '/api/resume-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateThreeRoute = ApiGenerateThreeRouteImport.update({
  id: '/api/generate-three',
  path: '/api/generate-three',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsIndexRoute = DemoGuitarsIndexRouteImport.update({
  id: '/demo/guitars/',
  path: '/demo/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsCompareRoute = DemoGuitarsCompareRouteImport.update({
  id: '/demo/guitars/compare',
  path: '/demo/guitars/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsGuitarIdRoute = DemoGuitarsGuitarIdRouteImport.update({
  id: '/demo/guitars/$guitarId',
  path: '/demo/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersTagsRoute = ApiWorkersTagsRouteImport.update({
  id: '/api/workers/tags',
  path: '/api/workers/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersSummaryRoute = ApiWorkersSummaryRouteImport.update({
  id: '/api/workers/summary',
  path: '/api/workers/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersSearchRoute = ApiWorkersSearchRouteImport.update({
  id: '/api/workers/search',
  path: '/api/workers/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersRecommendationsRoute =
  ApiWorkersRecommendationsRouteImport.update({
    id: '/api/workers/recommendations',
    path: '/api/workers/recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkersParseQueryRoute = ApiWorkersParseQueryRouteImport.update({
  id: '/api/workers/parse-query',
  path: '/api/workers/parse-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersEmbeddingsRoute = ApiWorkersEmbeddingsRouteImport.update({
  id: '/api/workers/embeddings',
  path: '/api/workers/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersChatRoute = ApiWorkersChatRouteImport.update({
  id: '/api/workers/chat',
  path: '/api/workers/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersCategorizeRoute = ApiWorkersCategorizeRouteImport.update({
  id: '/api/workers/categorize',
  path: '/api/workers/categorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTetrisLeaderboardRoute = ApiTetrisLeaderboardRouteImport.update({
  id: '/api/tetris/leaderboard',
  path: '/api/tetris/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardHistoryRoute = ApiLeaderboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApiLeaderboardRoute,
} as any)
const ApiGithubStatsRoute = ApiGithubStatsRouteImport.update({
  id: '/api/github/stats',
  path: '/api/github/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTtsStreamRoute = DemoApiAiTtsStreamRouteImport.update({
  id: '/demo/api/ai/tts-stream',
  path: '/demo/api/ai/tts-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTtsRoute = DemoApiAiTtsRouteImport.update({
  id: '/demo/api/ai/tts',
  path: '/demo/api/ai/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTranscriptionRoute = DemoApiAiTranscriptionRouteImport.update({
  id: '/demo/api/ai/transcription',
  path: '/demo/api/ai/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiStructuredRoute = DemoApiAiStructuredRouteImport.update({
  id: '/demo/api/ai/structured',
  path: '/demo/api/ai/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiSpeechRoute = DemoApiAiSpeechRouteImport.update({
  id: '/demo/api/ai/speech',
  path: '/demo/api/ai/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiPortfolioRoute = DemoApiAiPortfolioRouteImport.update({
  id: '/demo/api/ai/portfolio',
  path: '/demo/api/ai/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiImageRoute = DemoApiAiImageRouteImport.update({
  id: '/demo/api/ai/image',
  path: '/demo/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersEmbeddingsProtectedExampleRoute =
  ApiWorkersEmbeddingsProtectedExampleRouteImport.update({
    id: '/api/workers/embeddings-protected/example',
    path: '/api/workers/embeddings-protected/example',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTetrisLeaderboardHistoryRoute =
  ApiTetrisLeaderboardHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ApiTetrisLeaderboardRoute,
  } as any)
const DemoApiAiGuitarsSearchRoute = DemoApiAiGuitarsSearchRouteImport.update({
  id: '/demo/api/ai/guitars/search',
  path: '/demo/api/ai/guitars/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiGuitarsCompareRoute = DemoApiAiGuitarsCompareRouteImport.update({
  id: '/demo/api/ai/guitars/compare',
  path: '/demo/api/ai/guitars/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiGuitarsChatRoute = DemoApiAiGuitarsChatRouteImport.update({
  id: '/demo/api/ai/guitars/chat',
  path: '/demo/api/ai/guitars/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/chatbot': typeof ChatbotRoute
  '/journey': typeof JourneyRoute
  '/resume': typeof ResumeRoute
  '/tetris': typeof TetrisRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/generate-three': typeof ApiGenerateThreeRoute
  '/api/leaderboard': typeof ApiLeaderboardRouteWithChildren
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/api/resume-chat-stream': typeof ApiResumeChatStreamRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-portfolio': typeof DemoAiPortfolioRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/ai-tts': typeof DemoAiTtsRoute
  '/demo/ai-voice': typeof DemoAiVoiceRoute
  '/demo/pacer': typeof DemoPacerRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/api/github/stats': typeof ApiGithubStatsRoute
  '/api/leaderboard/history': typeof ApiLeaderboardHistoryRoute
  '/api/tetris/leaderboard': typeof ApiTetrisLeaderboardRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/workers/categorize': typeof ApiWorkersCategorizeRoute
  '/api/workers/chat': typeof ApiWorkersChatRoute
  '/api/workers/embeddings': typeof ApiWorkersEmbeddingsRoute
  '/api/workers/parse-query': typeof ApiWorkersParseQueryRoute
  '/api/workers/recommendations': typeof ApiWorkersRecommendationsRoute
  '/api/workers/search': typeof ApiWorkersSearchRoute
  '/api/workers/summary': typeof ApiWorkersSummaryRoute
  '/api/workers/tags': typeof ApiWorkersTagsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/guitars/compare': typeof DemoGuitarsCompareRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/api/tetris/leaderboard/history': typeof ApiTetrisLeaderboardHistoryRoute
  '/api/workers/embeddings-protected/example': typeof ApiWorkersEmbeddingsProtectedExampleRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/portfolio': typeof DemoApiAiPortfolioRoute
  '/demo/api/ai/speech': typeof DemoApiAiSpeechRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/api/ai/tts-stream': typeof DemoApiAiTtsStreamRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/demo/api/ai/guitars/chat': typeof DemoApiAiGuitarsChatRoute
  '/demo/api/ai/guitars/compare': typeof DemoApiAiGuitarsCompareRoute
  '/demo/api/ai/guitars/search': typeof DemoApiAiGuitarsSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/chatbot': typeof ChatbotRoute
  '/journey': typeof JourneyRoute
  '/resume': typeof ResumeRoute
  '/tetris': typeof TetrisRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/generate-three': typeof ApiGenerateThreeRoute
  '/api/leaderboard': typeof ApiLeaderboardRouteWithChildren
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/api/resume-chat-stream': typeof ApiResumeChatStreamRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-portfolio': typeof DemoAiPortfolioRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/ai-tts': typeof DemoAiTtsRoute
  '/demo/ai-voice': typeof DemoAiVoiceRoute
  '/demo/pacer': typeof DemoPacerRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/api/github/stats': typeof ApiGithubStatsRoute
  '/api/leaderboard/history': typeof ApiLeaderboardHistoryRoute
  '/api/tetris/leaderboard': typeof ApiTetrisLeaderboardRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/workers/categorize': typeof ApiWorkersCategorizeRoute
  '/api/workers/chat': typeof ApiWorkersChatRoute
  '/api/workers/embeddings': typeof ApiWorkersEmbeddingsRoute
  '/api/workers/parse-query': typeof ApiWorkersParseQueryRoute
  '/api/workers/recommendations': typeof ApiWorkersRecommendationsRoute
  '/api/workers/search': typeof ApiWorkersSearchRoute
  '/api/workers/summary': typeof ApiWorkersSummaryRoute
  '/api/workers/tags': typeof ApiWorkersTagsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/guitars/compare': typeof DemoGuitarsCompareRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/guitars': typeof DemoGuitarsIndexRoute
  '/api/tetris/leaderboard/history': typeof ApiTetrisLeaderboardHistoryRoute
  '/api/workers/embeddings-protected/example': typeof ApiWorkersEmbeddingsProtectedExampleRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/portfolio': typeof DemoApiAiPortfolioRoute
  '/demo/api/ai/speech': typeof DemoApiAiSpeechRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/api/ai/tts-stream': typeof DemoApiAiTtsStreamRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/demo/api/ai/guitars/chat': typeof DemoApiAiGuitarsChatRoute
  '/demo/api/ai/guitars/compare': typeof DemoApiAiGuitarsCompareRoute
  '/demo/api/ai/guitars/search': typeof DemoApiAiGuitarsSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/chatbot': typeof ChatbotRoute
  '/journey': typeof JourneyRoute
  '/resume': typeof ResumeRoute
  '/tetris': typeof TetrisRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/generate-three': typeof ApiGenerateThreeRoute
  '/api/leaderboard': typeof ApiLeaderboardRouteWithChildren
  '/api/resume-chat': typeof ApiResumeChatRoute
  '/api/resume-chat-stream': typeof ApiResumeChatStreamRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-portfolio': typeof DemoAiPortfolioRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/ai-tts': typeof DemoAiTtsRoute
  '/demo/ai-voice': typeof DemoAiVoiceRoute
  '/demo/pacer': typeof DemoPacerRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/trpc-todo': typeof DemoTrpcTodoRoute
  '/api/github/stats': typeof ApiGithubStatsRoute
  '/api/leaderboard/history': typeof ApiLeaderboardHistoryRoute
  '/api/tetris/leaderboard': typeof ApiTetrisLeaderboardRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/workers/categorize': typeof ApiWorkersCategorizeRoute
  '/api/workers/chat': typeof ApiWorkersChatRoute
  '/api/workers/embeddings': typeof ApiWorkersEmbeddingsRoute
  '/api/workers/parse-query': typeof ApiWorkersParseQueryRoute
  '/api/workers/recommendations': typeof ApiWorkersRecommendationsRoute
  '/api/workers/search': typeof ApiWorkersSearchRoute
  '/api/workers/summary': typeof ApiWorkersSummaryRoute
  '/api/workers/tags': typeof ApiWorkersTagsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/guitars/compare': typeof DemoGuitarsCompareRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/api/tetris/leaderboard/history': typeof ApiTetrisLeaderboardHistoryRoute
  '/api/workers/embeddings-protected/example': typeof ApiWorkersEmbeddingsProtectedExampleRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/portfolio': typeof DemoApiAiPortfolioRoute
  '/demo/api/ai/speech': typeof DemoApiAiSpeechRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
  '/demo/api/ai/tts-stream': typeof DemoApiAiTtsStreamRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/demo/api/ai/guitars/chat': typeof DemoApiAiGuitarsChatRoute
  '/demo/api/ai/guitars/compare': typeof DemoApiAiGuitarsCompareRoute
  '/demo/api/ai/guitars/search': typeof DemoApiAiGuitarsSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/chatbot'
    | '/journey'
    | '/resume'
    | '/tetris'
    | '/api/chat'
    | '/api/contact'
    | '/api/generate-three'
    | '/api/leaderboard'
    | '/api/resume-chat'
    | '/api/resume-chat-stream'
    | '/demo/ai-image'
    | '/demo/ai-portfolio'
    | '/demo/ai-structured'
    | '/demo/ai-tts'
    | '/demo/ai-voice'
    | '/demo/pacer'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/api/github/stats'
    | '/api/leaderboard/history'
    | '/api/tetris/leaderboard'
    | '/api/trpc/$'
    | '/api/workers/categorize'
    | '/api/workers/chat'
    | '/api/workers/embeddings'
    | '/api/workers/parse-query'
    | '/api/workers/recommendations'
    | '/api/workers/search'
    | '/api/workers/summary'
    | '/api/workers/tags'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/guitars/$guitarId'
    | '/demo/guitars/compare'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/guitars/'
    | '/api/tetris/leaderboard/history'
    | '/api/workers/embeddings-protected/example'
    | '/demo/api/ai/image'
    | '/demo/api/ai/portfolio'
    | '/demo/api/ai/speech'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/api/ai/tts-stream'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/demo/api/ai/guitars/chat'
    | '/demo/api/ai/guitars/compare'
    | '/demo/api/ai/guitars/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/chatbot'
    | '/journey'
    | '/resume'
    | '/tetris'
    | '/api/chat'
    | '/api/contact'
    | '/api/generate-three'
    | '/api/leaderboard'
    | '/api/resume-chat'
    | '/api/resume-chat-stream'
    | '/demo/ai-image'
    | '/demo/ai-portfolio'
    | '/demo/ai-structured'
    | '/demo/ai-tts'
    | '/demo/ai-voice'
    | '/demo/pacer'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/api/github/stats'
    | '/api/leaderboard/history'
    | '/api/tetris/leaderboard'
    | '/api/trpc/$'
    | '/api/workers/categorize'
    | '/api/workers/chat'
    | '/api/workers/embeddings'
    | '/api/workers/parse-query'
    | '/api/workers/recommendations'
    | '/api/workers/search'
    | '/api/workers/summary'
    | '/api/workers/tags'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/guitars/$guitarId'
    | '/demo/guitars/compare'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/guitars'
    | '/api/tetris/leaderboard/history'
    | '/api/workers/embeddings-protected/example'
    | '/demo/api/ai/image'
    | '/demo/api/ai/portfolio'
    | '/demo/api/ai/speech'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/api/ai/tts-stream'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/demo/api/ai/guitars/chat'
    | '/demo/api/ai/guitars/compare'
    | '/demo/api/ai/guitars/search'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/chatbot'
    | '/journey'
    | '/resume'
    | '/tetris'
    | '/api/chat'
    | '/api/contact'
    | '/api/generate-three'
    | '/api/leaderboard'
    | '/api/resume-chat'
    | '/api/resume-chat-stream'
    | '/demo/ai-image'
    | '/demo/ai-portfolio'
    | '/demo/ai-structured'
    | '/demo/ai-tts'
    | '/demo/ai-voice'
    | '/demo/pacer'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/trpc-todo'
    | '/api/github/stats'
    | '/api/leaderboard/history'
    | '/api/tetris/leaderboard'
    | '/api/trpc/$'
    | '/api/workers/categorize'
    | '/api/workers/chat'
    | '/api/workers/embeddings'
    | '/api/workers/parse-query'
    | '/api/workers/recommendations'
    | '/api/workers/search'
    | '/api/workers/summary'
    | '/api/workers/tags'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/guitars/$guitarId'
    | '/demo/guitars/compare'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/guitars/'
    | '/api/tetris/leaderboard/history'
    | '/api/workers/embeddings-protected/example'
    | '/demo/api/ai/image'
    | '/demo/api/ai/portfolio'
    | '/demo/api/ai/speech'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
    | '/demo/api/ai/tts-stream'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/demo/api/ai/guitars/chat'
    | '/demo/api/ai/guitars/compare'
    | '/demo/api/ai/guitars/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  ChatbotRoute: typeof ChatbotRoute
  JourneyRoute: typeof JourneyRoute
  ResumeRoute: typeof ResumeRoute
  TetrisRoute: typeof TetrisRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiGenerateThreeRoute: typeof ApiGenerateThreeRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRouteWithChildren
  ApiResumeChatRoute: typeof ApiResumeChatRoute
  ApiResumeChatStreamRoute: typeof ApiResumeChatStreamRoute
  DemoAiImageRoute: typeof DemoAiImageRoute
  DemoAiPortfolioRoute: typeof DemoAiPortfolioRoute
  DemoAiStructuredRoute: typeof DemoAiStructuredRoute
  DemoAiTtsRoute: typeof DemoAiTtsRoute
  DemoAiVoiceRoute: typeof DemoAiVoiceRoute
  DemoPacerRoute: typeof DemoPacerRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTrpcTodoRoute: typeof DemoTrpcTodoRoute
  ApiGithubStatsRoute: typeof ApiGithubStatsRoute
  ApiTetrisLeaderboardRoute: typeof ApiTetrisLeaderboardRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWorkersCategorizeRoute: typeof ApiWorkersCategorizeRoute
  ApiWorkersChatRoute: typeof ApiWorkersChatRoute
  ApiWorkersEmbeddingsRoute: typeof ApiWorkersEmbeddingsRoute
  ApiWorkersParseQueryRoute: typeof ApiWorkersParseQueryRoute
  ApiWorkersRecommendationsRoute: typeof ApiWorkersRecommendationsRoute
  ApiWorkersSearchRoute: typeof ApiWorkersSearchRoute
  ApiWorkersSummaryRoute: typeof ApiWorkersSummaryRoute
  ApiWorkersTagsRoute: typeof ApiWorkersTagsRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoGuitarsGuitarIdRoute: typeof DemoGuitarsGuitarIdRoute
  DemoGuitarsCompareRoute: typeof DemoGuitarsCompareRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoGuitarsIndexRoute: typeof DemoGuitarsIndexRoute
  ApiWorkersEmbeddingsProtectedExampleRoute: typeof ApiWorkersEmbeddingsProtectedExampleRoute
  DemoApiAiImageRoute: typeof DemoApiAiImageRoute
  DemoApiAiPortfolioRoute: typeof DemoApiAiPortfolioRoute
  DemoApiAiSpeechRoute: typeof DemoApiAiSpeechRoute
  DemoApiAiStructuredRoute: typeof DemoApiAiStructuredRoute
  DemoApiAiTranscriptionRoute: typeof DemoApiAiTranscriptionRoute
  DemoApiAiTtsRoute: typeof DemoApiAiTtsRoute
  DemoApiAiTtsStreamRoute: typeof DemoApiAiTtsStreamRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
  DemoApiAiGuitarsChatRoute: typeof DemoApiAiGuitarsChatRoute
  DemoApiAiGuitarsCompareRoute: typeof DemoApiAiGuitarsCompareRoute
  DemoApiAiGuitarsSearchRoute: typeof DemoApiAiGuitarsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tetris': {
      id: '/tetris'
      path: '/tetris'
      fullPath: '/tetris'
      preLoaderRoute: typeof TetrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/trpc-todo': {
      id: '/demo/trpc-todo'
      path: '/demo/trpc-todo'
      fullPath: '/demo/trpc-todo'
      preLoaderRoute: typeof DemoTrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/pacer': {
      id: '/demo/pacer'
      path: '/demo/pacer'
      fullPath: '/demo/pacer'
      preLoaderRoute: typeof DemoPacerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-voice': {
      id: '/demo/ai-voice'
      path: '/demo/ai-voice'
      fullPath: '/demo/ai-voice'
      preLoaderRoute: typeof DemoAiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-tts': {
      id: '/demo/ai-tts'
      path: '/demo/ai-tts'
      fullPath: '/demo/ai-tts'
      preLoaderRoute: typeof DemoAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-structured': {
      id: '/demo/ai-structured'
      path: '/demo/ai-structured'
      fullPath: '/demo/ai-structured'
      preLoaderRoute: typeof DemoAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-portfolio': {
      id: '/demo/ai-portfolio'
      path: '/demo/ai-portfolio'
      fullPath: '/demo/ai-portfolio'
      preLoaderRoute: typeof DemoAiPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-image': {
      id: '/demo/ai-image'
      path: '/demo/ai-image'
      fullPath: '/demo/ai-image'
      preLoaderRoute: typeof DemoAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-chat-stream': {
      id: '/api/resume-chat-stream'
      path: '/api/resume-chat-stream'
      fullPath: '/api/resume-chat-stream'
      preLoaderRoute: typeof ApiResumeChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-chat': {
      id: '/api/resume-chat'
      path: '/api/resume-chat'
      fullPath: '/api/resume-chat'
      preLoaderRoute: typeof ApiResumeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-three': {
      id: '/api/generate-three'
      path: '/api/generate-three'
      fullPath: '/api/generate-three'
      preLoaderRoute: typeof ApiGenerateThreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/': {
      id: '/demo/guitars/'
      path: '/demo/guitars'
      fullPath: '/demo/guitars/'
      preLoaderRoute: typeof DemoGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/compare': {
      id: '/demo/guitars/compare'
      path: '/demo/guitars/compare'
      fullPath: '/demo/guitars/compare'
      preLoaderRoute: typeof DemoGuitarsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/$guitarId': {
      id: '/demo/guitars/$guitarId'
      path: '/demo/guitars/$guitarId'
      fullPath: '/demo/guitars/$guitarId'
      preLoaderRoute: typeof DemoGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/tags': {
      id: '/api/workers/tags'
      path: '/api/workers/tags'
      fullPath: '/api/workers/tags'
      preLoaderRoute: typeof ApiWorkersTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/summary': {
      id: '/api/workers/summary'
      path: '/api/workers/summary'
      fullPath: '/api/workers/summary'
      preLoaderRoute: typeof ApiWorkersSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/search': {
      id: '/api/workers/search'
      path: '/api/workers/search'
      fullPath: '/api/workers/search'
      preLoaderRoute: typeof ApiWorkersSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/recommendations': {
      id: '/api/workers/recommendations'
      path: '/api/workers/recommendations'
      fullPath: '/api/workers/recommendations'
      preLoaderRoute: typeof ApiWorkersRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/parse-query': {
      id: '/api/workers/parse-query'
      path: '/api/workers/parse-query'
      fullPath: '/api/workers/parse-query'
      preLoaderRoute: typeof ApiWorkersParseQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/embeddings': {
      id: '/api/workers/embeddings'
      path: '/api/workers/embeddings'
      fullPath: '/api/workers/embeddings'
      preLoaderRoute: typeof ApiWorkersEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/chat': {
      id: '/api/workers/chat'
      path: '/api/workers/chat'
      fullPath: '/api/workers/chat'
      preLoaderRoute: typeof ApiWorkersChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/categorize': {
      id: '/api/workers/categorize'
      path: '/api/workers/categorize'
      fullPath: '/api/workers/categorize'
      preLoaderRoute: typeof ApiWorkersCategorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tetris/leaderboard': {
      id: '/api/tetris/leaderboard'
      path: '/api/tetris/leaderboard'
      fullPath: '/api/tetris/leaderboard'
      preLoaderRoute: typeof ApiTetrisLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard/history': {
      id: '/api/leaderboard/history'
      path: '/history'
      fullPath: '/api/leaderboard/history'
      preLoaderRoute: typeof ApiLeaderboardHistoryRouteImport
      parentRoute: typeof ApiLeaderboardRoute
    }
    '/api/github/stats': {
      id: '/api/github/stats'
      path: '/api/github/stats'
      fullPath: '/api/github/stats'
      preLoaderRoute: typeof ApiGithubStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/tts-stream': {
      id: '/demo/api/ai/tts-stream'
      path: '/demo/api/ai/tts-stream'
      fullPath: '/demo/api/ai/tts-stream'
      preLoaderRoute: typeof DemoApiAiTtsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/tts': {
      id: '/demo/api/ai/tts'
      path: '/demo/api/ai/tts'
      fullPath: '/demo/api/ai/tts'
      preLoaderRoute: typeof DemoApiAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/transcription': {
      id: '/demo/api/ai/transcription'
      path: '/demo/api/ai/transcription'
      fullPath: '/demo/api/ai/transcription'
      preLoaderRoute: typeof DemoApiAiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/structured': {
      id: '/demo/api/ai/structured'
      path: '/demo/api/ai/structured'
      fullPath: '/demo/api/ai/structured'
      preLoaderRoute: typeof DemoApiAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/speech': {
      id: '/demo/api/ai/speech'
      path: '/demo/api/ai/speech'
      fullPath: '/demo/api/ai/speech'
      preLoaderRoute: typeof DemoApiAiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/portfolio': {
      id: '/demo/api/ai/portfolio'
      path: '/demo/api/ai/portfolio'
      fullPath: '/demo/api/ai/portfolio'
      preLoaderRoute: typeof DemoApiAiPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/image': {
      id: '/demo/api/ai/image'
      path: '/demo/api/ai/image'
      fullPath: '/demo/api/ai/image'
      preLoaderRoute: typeof DemoApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/embeddings-protected/example': {
      id: '/api/workers/embeddings-protected/example'
      path: '/api/workers/embeddings-protected/example'
      fullPath: '/api/workers/embeddings-protected/example'
      preLoaderRoute: typeof ApiWorkersEmbeddingsProtectedExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tetris/leaderboard/history': {
      id: '/api/tetris/leaderboard/history'
      path: '/history'
      fullPath: '/api/tetris/leaderboard/history'
      preLoaderRoute: typeof ApiTetrisLeaderboardHistoryRouteImport
      parentRoute: typeof ApiTetrisLeaderboardRoute
    }
    '/demo/api/ai/guitars/search': {
      id: '/demo/api/ai/guitars/search'
      path: '/demo/api/ai/guitars/search'
      fullPath: '/demo/api/ai/guitars/search'
      preLoaderRoute: typeof DemoApiAiGuitarsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/guitars/compare': {
      id: '/demo/api/ai/guitars/compare'
      path: '/demo/api/ai/guitars/compare'
      fullPath: '/demo/api/ai/guitars/compare'
      preLoaderRoute: typeof DemoApiAiGuitarsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/guitars/chat': {
      id: '/demo/api/ai/guitars/chat'
      path: '/demo/api/ai/guitars/chat'
      fullPath: '/demo/api/ai/guitars/chat'
      preLoaderRoute: typeof DemoApiAiGuitarsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiLeaderboardRouteChildren {
  ApiLeaderboardHistoryRoute: typeof ApiLeaderboardHistoryRoute
}

const ApiLeaderboardRouteChildren: ApiLeaderboardRouteChildren = {
  ApiLeaderboardHistoryRoute: ApiLeaderboardHistoryRoute,
}

const ApiLeaderboardRouteWithChildren = ApiLeaderboardRoute._addFileChildren(
  ApiLeaderboardRouteChildren,
)

interface ApiTetrisLeaderboardRouteChildren {
  ApiTetrisLeaderboardHistoryRoute: typeof ApiTetrisLeaderboardHistoryRoute
}

const ApiTetrisLeaderboardRouteChildren: ApiTetrisLeaderboardRouteChildren = {
  ApiTetrisLeaderboardHistoryRoute: ApiTetrisLeaderboardHistoryRoute,
}

const ApiTetrisLeaderboardRouteWithChildren =
  ApiTetrisLeaderboardRoute._addFileChildren(ApiTetrisLeaderboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  ChatbotRoute: ChatbotRoute,
  JourneyRoute: JourneyRoute,
  ResumeRoute: ResumeRoute,
  TetrisRoute: TetrisRoute,
  ApiChatRoute: ApiChatRoute,
  ApiContactRoute: ApiContactRoute,
  ApiGenerateThreeRoute: ApiGenerateThreeRoute,
  ApiLeaderboardRoute: ApiLeaderboardRouteWithChildren,
  ApiResumeChatRoute: ApiResumeChatRoute,
  ApiResumeChatStreamRoute: ApiResumeChatStreamRoute,
  DemoAiImageRoute: DemoAiImageRoute,
  DemoAiPortfolioRoute: DemoAiPortfolioRoute,
  DemoAiStructuredRoute: DemoAiStructuredRoute,
  DemoAiTtsRoute: DemoAiTtsRoute,
  DemoAiVoiceRoute: DemoAiVoiceRoute,
  DemoPacerRoute: DemoPacerRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTrpcTodoRoute: DemoTrpcTodoRoute,
  ApiGithubStatsRoute: ApiGithubStatsRoute,
  ApiTetrisLeaderboardRoute: ApiTetrisLeaderboardRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWorkersCategorizeRoute: ApiWorkersCategorizeRoute,
  ApiWorkersChatRoute: ApiWorkersChatRoute,
  ApiWorkersEmbeddingsRoute: ApiWorkersEmbeddingsRoute,
  ApiWorkersParseQueryRoute: ApiWorkersParseQueryRoute,
  ApiWorkersRecommendationsRoute: ApiWorkersRecommendationsRoute,
  ApiWorkersSearchRoute: ApiWorkersSearchRoute,
  ApiWorkersSummaryRoute: ApiWorkersSummaryRoute,
  ApiWorkersTagsRoute: ApiWorkersTagsRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoGuitarsGuitarIdRoute: DemoGuitarsGuitarIdRoute,
  DemoGuitarsCompareRoute: DemoGuitarsCompareRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoGuitarsIndexRoute: DemoGuitarsIndexRoute,
  ApiWorkersEmbeddingsProtectedExampleRoute:
    ApiWorkersEmbeddingsProtectedExampleRoute,
  DemoApiAiImageRoute: DemoApiAiImageRoute,
  DemoApiAiPortfolioRoute: DemoApiAiPortfolioRoute,
  DemoApiAiSpeechRoute: DemoApiAiSpeechRoute,
  DemoApiAiStructuredRoute: DemoApiAiStructuredRoute,
  DemoApiAiTranscriptionRoute: DemoApiAiTranscriptionRoute,
  DemoApiAiTtsRoute: DemoApiAiTtsRoute,
  DemoApiAiTtsStreamRoute: DemoApiAiTtsStreamRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
  DemoApiAiGuitarsChatRoute: DemoApiAiGuitarsChatRoute,
  DemoApiAiGuitarsCompareRoute: DemoApiAiGuitarsCompareRoute,
  DemoApiAiGuitarsSearchRoute: DemoApiAiGuitarsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
